### PR TITLE
Add js_of_ocaml rule (#55)

### PR DESCRIPTION
**Pull request by copy**

### CODE REVIEW

**Comment by agarwal** [comment]
Thanks for this, and thanks especially for adding a corresponding demo. I'm wondering if we could put the new function in `Tools` instead of in `Project`. That's where other `_rule` functions are. So could we do this:

#### tools.mli
```ocaml
val js_of_ocaml_rule : (Pathname.t list -> Pathname.t -> Command.t) js_of_ocaml_args
```
Differences from your signature:
- I use `js_of_ocaml_args` to assure we capture all the possible labeled arguments without repeating them. Is that right? Your implementation doesn't allow the user to choose `linkall`, so maybe we really need a different set of args.
- Don't care if main file to compile is a lib or app. We just take any file path.

#### tools.ml
```ocaml
let js_of_ocaml_rule
  ?custom_header ?debug ?debug_info ?disable ?enable
  ?no_inline ?no_runtime ?o ?opt ?pretty ?quiet ?set
  ?source_map_inline ?source_map_no_source
  ?source_map_root ?source_map
  ?version ?extern_fs ?file ?pathI ?ofs
  ?linkall ?no_cmis ?toplevel
  extra_js dep
  =
  let base = chop_suffix dep in
  let prod = base ^ ".js" in
  let linkall = () in (* force this or let user select? *)
  Rule.rule path ~deps:[dep] ~prods:[prod] (fun _ _ ->
    Tools.js_of_ocaml
      ?custom_header ?debug ?debug_info ?disable ?enable
      ?no_inline ?no_runtime ?o ?opt ?pretty ?quiet ?set
      ?source_map_inline ?source_map_no_source
      ?source_map_root ?source_map
      ?version ?extern_fs ?file ?pathI ?ofs
      ?linkall ?no_cmis ?toplevel
      extra_js dep
    )
```
Differences from your implementation:
- Use `Rule.rule` instead of `Ocamlbuild_plugin.rule`. Not particularly important, but we use `Rule.rule` everywhere else, so this is more consistent.
- Compute `prod` file name differently since input isn't a `Project.item`.

**Comment by copy** [comment]
Glad to help!

> I use js_of_ocaml_args to assure we capture all the possible labeled arguments without repeating them. Is that right? Your implementation doesn't allow the user to choose linkall, so maybe we really need a different set of args.

That sounds good. I'm not entirely sure about the effect of `linkall`, so I wasn't quite sure how to handle it.

I like the approach of taking an `item`, because it doesn't require the user to know about the build process (for example, that `Project.lib "foo"` builds `foo.cma`, which is what `js_of_ocaml` takes as input). However, I understand the need for a low-level function that works on paths. I'd suggest we provide another rule function, `js_of_ocaml_rule_of_item : (Pathname.t list -> item -> unit) js_of_ocaml_args` for convenience.

**Comment by agarwal** [comment]
Okay, so feel free to add this to the `Project` module.

- The signature should be `(Pathname.t list -> item -> Command.t) Tools.js_of_ocaml_args`.

- The name should be `build_js`. I realize I've been inconsistent myself. The `Tools` module uses a `_rule` suffix for functions that register rules, but the `Project` module uses a `build_` prefix and the suffix is indicative of what gets built, a `js` file in this case. So I think `build_js` is the correct name.

If it's not too much trouble, please rebase the current master onto your branch since I've pushed several additional changes, and do a force push with your new changes so that we get a clean history for this pull request. Thanks.

**Comment by copy** [comment]
> The signature should be `(Pathname.t list -> item -> Command.t) Tools.js_of_ocaml_args`.

Shouldn't it be `unit` instead of `Command.t`?

> If it's not too much trouble, please rebase the current master onto your branch since I've pushed several additional changes, and do a force push with your new changes so that we get a clean history for this pull request. Thanks.

Will do. Just  a minor remark: Since we have two JavaScript backends (jsoo and bucklescript), maybe the name should include the backend name?

> I use js_of_ocaml_args to assure we capture all the possible labeled arguments without repeating them. Is that right? Your implementation doesn't allow the user to choose linkall, so maybe we really need a different set of args.

Now that I look at it again, there are certainly some arguments that shouldn't be in a rule function: `version`, `q`.

**Comment by agarwal** [comment]
> Shouldn't it be unit instead of Command.t?

Right.

> Since we have two JavaScript backends (jsoo and bucklescript), maybe the name should include the backend name?

Good point. Okay, so feel free to go with `build_js_of_ocaml` then.

> Now that I look at it again, there are certainly some arguments that shouldn't be in a rule function: version, q.

Rigt, so then you just have to list out all the args.

**Comment by copy** [comment]
@agarwal This should be good to merge

**Comment by agarwal** [comment]
Thanks!

**Pull request merged**
